/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openbravo.pos.config;

import com.openbravo.data.user.DirtyManager;
import com.openbravo.pos.forms.AppConfig;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.util.AltEncrypter;
import com.openbravo.pos.util.DirectoryEvent;
import java.awt.Component;

/**
 *
 * @author np370
 */
public class JPanelConfigEmail extends javax.swing.JPanel implements PanelConfig {
    
    private DirtyManager dirty = new DirtyManager();
    

    /**
     * Creates new form JPanelConfigEmail
     */
    public JPanelConfigEmail() {
        initComponents();
        jtxtEmail.getDocument().addDocumentListener(dirty);
        jcboEmail.addActionListener(dirty);
        jtxtAccountMail.getDocument().addDocumentListener(dirty);
        jtxtEmailPassword.getDocument().addDocumentListener(dirty);
    }
    
    @Override
    public boolean hasChanged() {
        return dirty.isDirty();
    }
    @Override
    public Component getConfigComponent() {
        return this;
    }
     @Override
    public void loadProperties(AppConfig config) {                        
        String email = config.getProperty("email.mail");
        String jcboAccount = config.getProperty("email.accountdomain");
        String txtEmailAccout = config.getProperty("email.account");
        String pass = config.getProperty("email.password");
        if (txtEmailAccout != null && pass != null && pass.startsWith("crypt:") ) {
             // La clave esta encriptada.
            AltEncrypter cypher = new AltEncrypter("cypherkey" + txtEmailAccout);
            pass = cypher.decrypt(pass.substring(6));
        }        
        jtxtEmail.setText(email);
        jcboEmail.setSelectedItem(config.getProperty("email.accountdomain"));
        jtxtAccountMail.setText(txtEmailAccout);
        jtxtEmailPassword.setText(pass);
        dirty.setDirty(false);
    }
    @Override
    public void saveProperties(AppConfig config) {        
        config.setProperty("email.mail", jtxtEmail.getText());
        config.setProperty("email.accountdomain", comboValue(jcboEmail.getSelectedItem()));
        config.setProperty("email.account",jtxtAccountMail.getText());
        AltEncrypter cypher = new AltEncrypter("cypherkey" + jtxtAccountMail.getText());
        config.setProperty("email.password", "crypt:" + cypher.encrypt(new String(jtxtEmailPassword.getPassword())));
        dirty.setDirty(false);
    }
    private String comboValue(Object value) {
        return value == null ? "" : value.toString();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcboEmail = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jtxtEmailPassword = new javax.swing.JPasswordField();
        jtxtAccountMail = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(698, 226));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        jPanel1.setPreferredSize(new java.awt.Dimension(678, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Email para recibir reportes");

        jLabel2.setText("Cuenta para enviar correos");

        jcboEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcboEmail.setMaximumRowCount(3);
        jcboEmail.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "gmail.com", "yahoo.com" }));

        jLabel3.setText("Password");

        jtxtEmailPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(jtxtEmailPassword))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtAccountMail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jcboEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcboEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAccountMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtEmailPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcboEmail;
    private javax.swing.JTextField jtxtAccountMail;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JPasswordField jtxtEmailPassword;
    // End of variables declaration//GEN-END:variables
}
